#!/bin/bash -l

TESTS="${1?Specify a test package}"

export CXF_VERSION="${CXF_VERSION:-3.4.4-SNAPSHOT}"
export GF_VERSION="5.1.0"
export GF_DIR="glassfish5"


##[ Imports ]####################

source "$(dirname $0)/setup.sh"

##[ Required Environment ]#######

export WORKSPACE=$PWD
export ANT_OPTS="-Djavax.xml.accessExternalSchema=all"
export TESTS="${TESTS//.//}"
export TS_HOME="${WORKSPACE}/restful-ws-tck"
export javaee_home="${WORKSPACE}/$GF_DIR"
export GF_HOME="${WORKSPACE}/$GF_DIR/glassfish"
export AS_JAVA="${JAVA_HOME?Env variable must be set}"
export deliverabledir="jaxrs"

##[ Set Defaults ]###############

[[ ! -d "$M2_HOME" && -d "$MAVEN_HOME" ]] && {
    export M2_HOME="$MAVEN_HOME"
}

[[ ! -d "$ANT_HOME" && -d "$WORKSPACE/apache-ant-1.10.9" ]] && {
    export ANT_HOME="$WORKSPACE/apache-ant-1.10.9"
}

##[ Run Setup ]##################

setuptck

##[ Show Environment ]###########

echo "TESTS = $TESTS"
echo "M2_HOME = ${M2_HOME?Env variable required}"
echo "JAVA_HOME = ${JAVA_HOME?Env variable required}"
echo "ANT_HOME = ${ANT_HOME?Env variable required}"
echo "WORKSPACE = ${WORKSPACE}"

java -version
ant -version
mvn -version


##[ Clean Previous Run ]#########

[ -d target ] && rm -rf target
mkdir target


##[ Run ]########################

(cd "${TS_HOME}/bin" 
 ant config.vi 
 ant deploy.all

 echo -e "\n---[ Begin Running Tests ]---\n"
 ant run.all         -Dall.test.dir="$TESTS" \
     -Dcts.jtroutput=true 2>&1 | tee "$WORKSPACE/target/javatest.log" | grep 'Finished Test'

 echo -e "\n---[ End Running Tests ]---\n"

 ant stop-server -f xml/impl/glassfish/config.vi.xml

)

mv /tmp/JT* target/
