#!/bin/bash

TESTS="${1?Specify a test package}"

CXF_VERSION="3.4.4-SNAPSHOT"
GF_VERSION="5.1.0"
GF_DIR="glassfish5"


##[ Imports ]####################

#source "$(dirname $0)/setup.sh"

##[ Required Environment ]#######

export WORKSPACE=$PWD
export ANT_OPTS="-Djavax.xml.accessExternalSchema=all"
export TESTS="${TESTS//.//}"
export TS_HOME="${WORKSPACE}/restful-ws-tck"
export javaee_home="${WORKSPACE}/$GF_DIR"
export GF_HOME="${WORKSPACE}/$GF_DIR/glassfish"
export AS_JAVA="${JAVA_HOME?Env variable must be set}"
export deliverabledir="jaxrs"

##[ Run Setup ]##################

#setup

##[ Show Environment ]###########

echo "TESTS = $TESTS"
echo "M2_HOME = ${M2_HOME?Env variable required}"
echo "JAVA_HOME = ${JAVA_HOME?Env variable required}"
echo "ANT_HOME = ${ANT_HOME?Env variable required}"
echo "WORKSPACE = ${WORKSPACE}"

java -version
ant -version
mvn -version


##[ Clean Previous Run ]#########

[ -d target ] && rm -rf target
mkdir target


##[ Run ]########################

(cd "${TS_HOME}/bin" 
 ant config.vi 
 ant deploy.all
 ant run.all \
     -Dall.test.dir="$TESTS" \
     -Dcts.jtroutput=true
 
 ant stop-server -f xml/impl/glassfish/config.vi.xml

) 2>&1 | tee target/javatest.log \
    | grep "Finished Test" \
    | perl -pe 's,.*Finished Test:,,'

mv /tmp/JT* target/
